# Generated by Django 4.2.9 on 2026-03-11 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_estimateitem_hsn_sac_code_invoiceitem_hsn_sac_code_and_more'),
        ('payments', '0002_payment_custom_field_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proforma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='invoices.proformainvoice'),
        ),
    ]
