# Generated by Django 4.2.9 on 2026-03-11 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_estimateitem_hsn_sac_code_invoiceitem_hsn_sac_code_and_more'),
        ('payments', '0004_alter_payment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='finalinvoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='invoices.finalinvoice'),
        ),
    ]
