# Generated by Django 4.2.9 on 2026-09-22 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_currency_custom_field_values'),
        ('order_returns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreturn',
            name='currency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
        migrations.AddIndex(
            model_name='orderreturn',
            index=models.Index(fields=['-date'], name='order_retur_date_7eecc9_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreturn',
            index=models.Index(fields=['return_type'], name='order_retur_return__4bf3d6_idx'),
        ),
    ]
