# Generated by Django 4.2.9 on 2026-02-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_billing_address_vendor_return_policy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='website',
        ),
    ]
