# Generated by Django 4.2.9 on 2026-09-22 10:07

import apps.customer_pos.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_pos', '0003_customerpo_custom_field_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpo',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='customer_pos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xlsx', 'xls', 'csv', 'doc', 'docx']), apps.customer_pos.models.validate_attachment_size]),
        ),
    ]
