# Generated by Django 4.2.9 on 2026-03-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debit_notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnoteitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
