# Generated by Django 4.2.9 on 2026-03-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debit_notes', '0002_debitnoteitem_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnoteitem',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
