# Generated by Django 4.2.9 on 2026-02-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
