# Generated by Django 4.2.9 on 2026-09-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_operations', '0002_alter_importhistory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
