# Generated by Django 4.2.9 on 2026-09-29 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0003_role_custom_field_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('account_created', 'Account created (with credentials)'), ('password_changed', 'Password changed confirmation'), ('new_rfq', 'New RFQ created (staff)'), ('rfq_status_change', 'RFQ status changed (staff)')], db_index=True, max_length=30)),
                ('recipients', models.TextField(help_text='Comma-separated recipient addresses')),
                ('subject', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], db_index=True, max_length=10)),
                ('error', models.TextField(blank=True)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email log',
                'verbose_name_plural': 'Email logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_entry', to='roles.role')),
            ],
            options={
                'ordering': ['role__name'],
            },
        ),
    ]
