# Generated by Django 4.2.9 on 2026-03-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_alter_permission_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='custom_field_values',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
