# Generated by Django 4.2.9 on 2026-09-29 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_date', models.DateField(auto_now_add=True)),
                ('total_customers', models.PositiveIntegerField(default=0)),
                ('total_vendors', models.PositiveIntegerField(default=0)),
                ('total_invoices', models.PositiveIntegerField(default=0)),
                ('total_purchase_orders', models.PositiveIntegerField(default=0)),
                ('revenue_today', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('revenue_this_month', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('revenue_this_year', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payments_received_today', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payments_received_month', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('overdue_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'ordering': ['-metric_date'],
            },
        ),
        migrations.CreateModel(
            name='VendorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_purchase_orders', models.PositiveIntegerField(default=0)),
                ('total_purchase_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_pending', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('summary_data', models.JSONField(default=dict, help_text='Spending per vendor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_received', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_pending', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_overdue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('summary_data', models.JSONField(default=dict, help_text='Payment details by method, status, etc.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('current_0_30_days', models.DecimalField(decimal_places=2, default=0, help_text='Amount due in 0-30 days', max_digits=14)),
                ('current_31_60_days', models.DecimalField(decimal_places=2, default=0, help_text='Amount due in 31-60 days', max_digits=14)),
                ('current_61_90_days', models.DecimalField(decimal_places=2, default=0, help_text='Amount due in 61-90 days', max_digits=14)),
                ('overdue_90_plus', models.DecimalField(decimal_places=2, default=0, help_text='Amount overdue 90+ days', max_digits=14)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('summary_data', models.JSONField(default=dict, help_text='Detailed invoice list by age bucket')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='TaxReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_taxable_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_tax_collected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_taxable_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_tax_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_tax_payable', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('summary_data', models.JSONField(default=dict, help_text='GST breakdown by rate/type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end'],
                'unique_together': {('period_type', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('daily', 'Daily Sales'), ('weekly', 'Weekly Sales'), ('monthly', 'Monthly Sales'), ('quarterly', 'Quarterly Sales'), ('yearly', 'Yearly Sales'), ('by_customer', 'Sales by Customer'), ('by_product', 'Sales by Product')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_invoices', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('summary_data', models.JSONField(default=dict, help_text='Aggregated data per period/customer/product')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type', '-created_at'], name='reports_sal_report__6e7313_idx'), models.Index(fields=['start_date', 'end_date'], name='reports_sal_start_d_de74dd_idx')],
            },
        ),
    ]
