# Generated by Django 4.2.9 on 2026-03-09 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_currency_custom_field_values'),
        ('rfq', '0003_alter_rfq_id_alter_rfqitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='currencies.currency'),
        ),
        migrations.AlterField(
            model_name='rfqitem',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
