# Generated by Django 4.2.9 on 2026-09-22 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendor_website'),
        ('rfq', '0004_rfq_currency_alter_rfqitem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('responded', 'Responded'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('response_deadline', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_to_po_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='rfq.rfq')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfq_responses', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('rfq', 'vendor')},
            },
        ),
        migrations.CreateModel(
            name='RFQResponseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rfq.rfqresponse')),
                ('rfq_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rfq.rfqitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
