# Generated by Django 4.2.9 on 2026-03-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='custom_field_values',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
