
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ("customers", "0001_initial"),
        ("vendors", "0001_initial"),
        ("pdf_templates", "0001_initial"),
    ]
    operations = [
        # Estimate
        migrations.CreateModel(
            name="Estimate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_field_values", models.JSONField(blank=True, default=dict)),
                ("date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("draft","Draft"),("sent","Sent"),("paid","Paid"),("partial","Partially Paid"),("overdue","Overdue"),("cancelled","Cancelled")], default="draft", max_length=20)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("terms", models.TextField(blank=True)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("discount_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("paid_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("estimate_number", models.CharField(max_length=50, unique=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="customers.customer")),
                ("pdf_template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="pdf_templates.pdftemplate")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="EstimateItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=500)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(blank=True, max_length=30)),
                ("unit_price", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("tax_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("order", models.PositiveIntegerField(default=0)),
                ("estimate", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="invoices.estimate")),
            ],
            options={"ordering": ["order"], "abstract": False},
        ),
        # Invoice
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_field_values", models.JSONField(blank=True, default=dict)),
                ("date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("draft","Draft"),("sent","Sent"),("paid","Paid"),("partial","Partially Paid"),("overdue","Overdue"),("cancelled","Cancelled")], default="draft", max_length=20)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("terms", models.TextField(blank=True)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("discount_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("paid_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="customers.customer")),
                ("estimate", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="invoices", to="invoices.estimate")),
                ("pdf_template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="pdf_templates.pdftemplate")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=500)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(blank=True, max_length=30)),
                ("unit_price", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("tax_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("order", models.PositiveIntegerField(default=0)),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="invoices.invoice")),
            ],
            options={"ordering": ["order"], "abstract": False},
        ),
        # ProformaInvoice
        migrations.CreateModel(
            name="ProformaInvoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_field_values", models.JSONField(blank=True, default=dict)),
                ("date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("draft","Draft"),("sent","Sent"),("paid","Paid"),("partial","Partially Paid"),("overdue","Overdue"),("cancelled","Cancelled")], default="draft", max_length=20)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("terms", models.TextField(blank=True)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("discount_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("paid_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("proforma_number", models.CharField(max_length=50, unique=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="customers.customer")),
                ("pdf_template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="pdf_templates.pdftemplate")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ProformaInvoiceItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=500)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(blank=True, max_length=30)),
                ("unit_price", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("tax_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("order", models.PositiveIntegerField(default=0)),
                ("proforma", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="invoices.proformainvoice")),
            ],
            options={"ordering": ["order"], "abstract": False},
        ),
        # PurchaseOrder
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_field_values", models.JSONField(blank=True, default=dict)),
                ("po_number", models.CharField(max_length=50, unique=True)),
                ("date", models.DateField()),
                ("expected_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("draft","Draft"),("approved","Approved"),("sent","Sent to Vendor"),("received","Received"),("cancelled","Cancelled")], default="draft", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("terms", models.TextField(blank=True)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("vendor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchase_orders", to="vendors.vendor")),
                ("pdf_template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="pdf_templates.pdftemplate")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=500)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(blank=True, max_length=30)),
                ("unit_price", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("tax_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("order", models.PositiveIntegerField(default=0)),
                ("purchase_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="invoices.purchaseorder")),
            ],
            options={"ordering": ["order"], "abstract": False},
        ),
        # FinalInvoice
        migrations.CreateModel(
            name="FinalInvoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_field_values", models.JSONField(blank=True, default=dict)),
                ("date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("draft","Draft"),("sent","Sent"),("paid","Paid"),("partial","Partially Paid"),("overdue","Overdue"),("cancelled","Cancelled")], default="draft", max_length=20)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("terms", models.TextField(blank=True)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("discount_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("paid_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("final_number", models.CharField(max_length=50, unique=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="customers.customer")),
                ("invoice", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="final_invoices", to="invoices.invoice")),
                ("proforma", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="final_invoices", to="invoices.proformainvoice")),
                ("pdf_template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="pdf_templates.pdftemplate")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="FinalInvoiceItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=500)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(blank=True, max_length=30)),
                ("unit_price", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("tax_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("order", models.PositiveIntegerField(default=0)),
                ("final_invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="invoices.finalinvoice")),
            ],
            options={"ordering": ["order"], "abstract": False},
        ),
    ]
