# Generated by Django 4.2.9 on 2026-03-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalinvoice',
            name='HSN_SAC_code',
            field=models.CharField(blank=True, max_length=900),
        ),
    ]
