# Generated by Django 4.2.9 on 2026-03-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_finalinvoice_hsn_sac_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalinvoice',
            name='HSN_SAC_code',
        ),
        migrations.AddField(
            model_name='finalinvoiceitem',
            name='HSN_SAC_code',
            field=models.CharField(blank=True, max_length=900),
        ),
    ]
