# Generated by Django 4.2.9 on 2026-02-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_purchaseorder_po_reference_alter_estimate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('UNPAID', 'UNPAID')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='finalinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('UNPAID', 'UNPAID')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('UNPAID', 'UNPAID')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('UNPAID', 'UNPAID')], default='draft', max_length=20),
        ),
    ]
