# Generated by Django 4.2.9 on 2026-03-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_finalinvoice_hsn_sac_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateitem',
            name='HSN_SAC_code',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='HSN_SAC_code',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='HSN_SAC_code',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='HSN_SAC_code',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='finalinvoiceitem',
            name='HSN_SAC_code',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
