# Generated by Django 4.2.9 on 2026-02-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_estimate_status_alter_finalinvoice_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateitem',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='finalinvoiceitem',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='proformainvoiceitem',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
